USE [prueba3]
GO
/****** Object:  Table [dbo].[ARTICULO]    Script Date: 13/11/2023 21:05:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ARTICULO](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[idtipo] [int] NULL,
	[descripcion] [varchar](50) NOT NULL,
	[precio] [money] NULL,
 CONSTRAINT [pk_idarticulo] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tipo]    Script Date: 13/11/2023 21:05:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tipo](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[descripcion] [text] NOT NULL,
 CONSTRAINT [pk_idtipo] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[ARTICULO] ADD  CONSTRAINT [df_precio]  DEFAULT ((0)) FOR [precio]
GO
ALTER TABLE [dbo].[ARTICULO]  WITH CHECK ADD  CONSTRAINT [fk_idtipo] FOREIGN KEY([idtipo])
REFERENCES [dbo].[tipo] ([id])
GO
ALTER TABLE [dbo].[ARTICULO] CHECK CONSTRAINT [fk_idtipo]
GO
/****** Object:  StoredProcedure [dbo].[ACTUALIZAR]    Script Date: 13/11/2023 21:05:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
      CREATE PROCEDURE [dbo].[ACTUALIZAR]
   @CODIGO INT, 
   @DESCRIPCION  VARCHAR(50),
   @PRECIO MONEY,
   @TIPO INT
 AS 
   BEGIN 
     UPDATE ARTICULO SET DESCRIPCION = @DESCRIPCION, PRECIO=@PRECIO, IDTIPO=@TIPO WHERE ID = @CODIGO
   END
GO
/****** Object:  StoredProcedure [dbo].[BORRAR]    Script Date: 13/11/2023 21:05:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
   CREATE PROCEDURE [dbo].[BORRAR]
   @CODIGO INT 
 AS 
   BEGIN 
      DELETE ARTICULO WHERE ID = @CODIGO
   END
GO
/****** Object:  StoredProcedure [dbo].[BORRARTIPO]    Script Date: 13/11/2023 21:05:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
    CREATE PROCEDURE [dbo].[BORRARTIPO]
   @CODIGO INT 
 AS 
   BEGIN 
      DELETE TIPO WHERE ID = @CODIGO
   END
GO
/****** Object:  StoredProcedure [dbo].[CONSULTAR]    Script Date: 13/11/2023 21:05:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[CONSULTAR]
 AS 
   BEGIN 
      SELECT * FROM ARTICULO
   END
GO
/****** Object:  StoredProcedure [dbo].[CONSULTAR_FILTRO]    Script Date: 13/11/2023 21:05:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
   CREATE PROCEDURE [dbo].[CONSULTAR_FILTRO]
   @CODIGO INT 
 AS 
   BEGIN 
      SELECT * FROM ARTICULO WHERE ID = @CODIGO
   END
GO
/****** Object:  StoredProcedure [dbo].[CONSULTAR_FILTROTIPOS]    Script Date: 13/11/2023 21:05:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
  CREATE PROCEDURE [dbo].[CONSULTAR_FILTROTIPOS]
   @CODIGO INT 
 AS 
   BEGIN 
      SELECT * FROM TIPO WHERE ID = @CODIGO
   END
GO
/****** Object:  StoredProcedure [dbo].[INGRESAR]    Script Date: 13/11/2023 21:05:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[INGRESAR]
   @DESCRIPCION  VARCHAR(50),
   @PRECIO MONEY,
   @TIPO INT
 AS 
   BEGIN 
     INSERT INTO  ARTICULO (DESCRIPCION, PRECIO, IDTIPO) VALUES (@DESCRIPCION,@PRECIO,@TIPO)
   END
GO
/****** Object:  StoredProcedure [dbo].[INGRESARTIPO]    Script Date: 13/11/2023 21:05:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[INGRESARTIPO]
   @DESCRIPCION  VARCHAR(50)
  
 AS 
   BEGIN 
     INSERT INTO TIPO (DESCRIPCION) VALUES (@DESCRIPCION)
   END
GO
